---
title: "Title of Report"
date: last-modified
date-format: "MMMM D, YYYY"
author: 
    - name: Libby Brill
      affil-id: 1
    - name: Sophia Freije
      affil-id: 1
    - name: Jett Palmer
      affil-id: 1
    - name: Alea Seifert
      affil-id: 1
affiliations:
    - id: 1
      name: Department of Statistics, Cal Poly - SLO
abstract: "The London Fire Brigade (LBF) is a firefighting and rescue organization that receives various calls regarding animal rescues from London citizens. Within the LBF recorded rescues, spanning from 2009 to 2020, there was a noticeable difference observed in the number of wild animals (n = 4668) and pet calls (n = 1898). We analyzed data using statistical software to understand the impact of time on the frequency of animal rescues based on animal type. Through a two-proportion z-test, we found a discernible difference in the percentage of night-time incidents comparing pets and wild animals. With a broad span of services conducted by the LBF, information regarding the frequency of pet rescues during the night-time is helpful when allocating resources and scheduling staff. This allows the LBF to be better equipped to handle pet rescue incidents most efficiently during the night shift."
format: 
  pdf:
    number-sections: true
    template-partials: 
      - title.tex
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
execute: 
  warning: false
  message: false
  echo: false
bibliography: references.bib
---

```{r}
#| label: setup
library(tidyverse)
library(ggrepel)
library(ggtext)
```

```{r}
#| label: data-cleaning
# Data Cleaning

source("data_cleaning.R")

animals_clean <- animals |>
  filter(cal_year < 2021) |>
  mutate(date_time_of_call = dmy_hm(date_time_of_call),
         day_time = if_else(hour(date_time_of_call) < 6 | hour(date_time_of_call) >= 18, "Night", "Day")) |>
  filter(animal_group_parent %in% c("Cat", "Dog", "Rabbit", "Bird", "Fox", "Deer")) |>
  mutate(animal_category = case_when(animal_group_parent == "Cat" ~ "Pet",
                                     animal_group_parent == "Dog" ~ "Pet",
                                     animal_group_parent == "Rabbit" ~ "Pet",
                                     animal_group_parent == "Bird" ~ "Wild",
                                     animal_group_parent == "Fox" ~ "Wild",
                                     animal_group_parent == "Deer" ~ "Wild")) |>
  group_by(cal_year, day_time, animal_category) |>
  count() |>
  pivot_wider(names_from = c(animal_category, day_time),
              values_from = n) |>
  mutate(Pets = Pet_Night / (Pet_Day + Pet_Night),
         `Wild Animals` = Wild_Night / (Wild_Day + Wild_Night)) |>
  select(cal_year, Pets, `Wild Animals`) |>
  pivot_longer(cols = Pets:`Wild Animals`,
               names_to = "Animal_Category",
               values_to = "Prop_Night")

```

```{r, results='hide'}
#| label: data-analysis
# you might choose to run your analysis here or in a separate script. Save your output for later.

prop.test(x = c(1636, 570), n= c(4668, 1898), alternative = "greater") 
```

## Introduction {#intro}

According to @tuan2015, it is said to xxx. Supported by this we found xyz [@wiwanitkit2010dengue].

## Data and Methods

### Data Collection

### Statistical Analysis

## Results {#results}


```{r}
#| label: fig-night-animal
#| fig-cap: "The figure represents the percentage of night-time animal rescues by the London Fire Brigade from 2009 to 2020. Grouped by pets (cat, dog, rabbit) and wild animals (bird, fox, deer), the plot reveals that the percent of pet night rescues is larger than wildlife night rescues across all years."
#| fig-alt: "The graph depicts a line chart with the x-axis as year, from 2009 to 2020, and the percent of night-time rescues, from 0 percent to 50 percent. There are two lines on the graph, one depicting percentage of night-time rescues of pets over time in orange and the other is depicting percentage of night-time rescues of wild animals over time in blue. Overall, the pet line appears to be slightly higher than the wild animal line for all years, with some variation."
#| fig-align: center
#| fig-pos: "H"

animals_clean |>
  ggplot(aes(x = cal_year, y = Prop_Night, color = Animal_Category)) +
  geom_line(aes(linetype = Animal_Category, color = Animal_Category), linewidth = 0.75, show.legend = FALSE) +
  geom_point(aes(shape = Animal_Category, color = Animal_Category), size = 2.5, show.legend = FALSE) +
  labs(title = "<span style='color: orange3;'>Pets</span> exceed <span style='color: steelblue;'>Wild Animals</span> in % of Night-time Rescues over Time",
       y = "",
       x = "",
       #subtitle = "Percentage of Night-time Rescues",
       linetype = "Animal Type",
       color = "Animal Type",
       shape = "Animal Type",
       caption = "Data Source: London Data Store") +
  scale_x_continuous(breaks = c(2010, 2012, 2014, 2016, 2018, 2020), minor_breaks = NULL) +
  scale_y_continuous(limits = c(0, 0.5), minor_breaks = NULL, labels = scales::percent) +
  theme_bw() +
  theme(#legend.position = c(0.8, 0.20),
  #  legend.box.background = element_rect(color = "black"),
   plot.title = element_markdown(hjust = 0.5)) +
  scale_color_manual(values = c("orange3", "steelblue")) +
  scale_linetype_manual(values = c("solid", "dashed")) +
  scale_shape_manual(values = c(17, 16))
```


```{r}
#| label: tbl-night-summary
#| tbl-cap: "The table depicts the percentage of night-time animal rescues by the London Fire Brigade from 2009 to 2020 of pets and wild animals. The table also includes the total number of calls for each group."
#| tbl-pos: "H"

animals |>
  filter(cal_year < 2021) |>
  mutate(date_time_of_call = dmy_hm(date_time_of_call),
         day_time = if_else(hour(date_time_of_call) < 6 | hour(date_time_of_call) >= 18, "Night", "Day")) |>
  filter(animal_group_parent %in% c("Cat", "Dog", "Rabbit", "Bird", "Fox", "Deer")) |>
  mutate(Animal_Category = case_when(animal_group_parent == "Cat" ~ "Pets",
                                     animal_group_parent == "Dog" ~ "Pets",
                                     animal_group_parent == "Rabbit" ~ "Pets",
                                     animal_group_parent == "Bird" ~ "Wild Animals",
                                     animal_group_parent == "Fox" ~ "Wild Animals",
                                     animal_group_parent == "Deer" ~ "Wild Animals")) |>
  group_by(day_time, Animal_Category) |>
  count() |>
pivot_wider(id_cols = Animal_Category, names_from = day_time, values_from = n) |>
  mutate(Total = Day + Night,
         Night_Prop = (Night / Total)) |>
  select(Animal_Category, Night_Prop, Total) |>
  mutate(Night_Prop = scales::percent(Night_Prop, accuracy = 0.1)) |> 
  kableExtra::kbl(
                  col.names = c("Animal Type", 
                                "% of Rescues Occuring at Night",
                                "Total Number of Animals"),
                  align = c("l", "c", "c"),
                  booktabs = TRUE
                  )

```

```{r}
#| label: fig-cl
#| fig-cap: "The figure represents the 95% confidence interval for the propotion of night-time rescues for each pets and wild animals. "
# Number of nighttime in each sample
pet <- 1636
wild <- 570

# Total number of animals in each sample
n_pet <- 4668
n_wild <- 1898

# Calculate sample proportions
p1 <- pet / n_pet
p2 <- wild / n_wild

# Confidence Intervals
result1 <- prop.test(pet, n_pet)
result2 <- prop.test(wild, n_wild)

cl_animal <- data.frame(animal_type = c("Pets", "Wild Animals"),
                        lower = c(0.3368063, 0.2798561),
                        upper = c(0.3643841, 0.3215931),
                        prop = c(p1, p2))

ggplot(cl_animal, aes(x = animal_type)) +
  geom_point(aes(y = prop), size = 4) +  # Specify y value here
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  labs(title = "95% Confidence Intervals for Night-time Rescues",
       subtitle = "Confidence Interval",
       x = "Animal Type",
       y = "") +
  theme_bw()
```

## Discussion {#discussion}
@tbl-night-summary
@fig-night-animal

## Conclusion {#conclusion}

## References {.unnumbered}
