---
title: "CP1: Data Proposal"
format: pdf
editor: visual
self-contained: true
authors: "Alea Seifert, Jett Palmer, Libby Brill, Sophia Freije"
---

## Data Set

```{r}
#| message: false
source("data_cleaning.R")
```

The [Animal Rescues](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-06-29/readme.md) data set was posted on June 29th, 2021 to the Tidy Tuesday GitHub repository by Georgios Karamanis and *Data is Plural*. The data were collected starting in January of 2009 by the London Fire Brigade (LFB) and is updated monthly to the [London Data Store](https://data.london.gov.uk/dataset/animal-rescue-incidents-attended-by-lfb). Each observational unit is an LFB response to an animal incident call. The data are collected across London (within LFB jurisdiction) and contain 31 variables (10 numeric, 21 categorical).

Variables include information about each incident such as incident ID and the date/time of the call. The dataset has multiple variables about the location of the incident including specific coordinates of longitude and latitude as well as the broader postal code and street name. However, we will be using the borough where the incident occurred as our main location indicator. There are also multiple variables surrounding the incident attributes that were recorded. We will be focusing on the special service type category which includes information about how the animal was rescued such as "animal rescued from water" or "animal rescued from height". However, it is important to note that the data set does not include information on animal deaths or injuries. Additionally, the LFB noted the type of animal(s) rescued under special service type variables like bird, domestic pet, or farm animal. The data set also logs the cost of each incident rescue in British pounds.

## Research Questions

1.  How has the frequency of animal rescues changed from pre-pandemic to post-panedmic among different animals?

    May include: `cal_year` (calendar year), `animal_group_parent` (type of animal)

    Tentative plan: Create a pandemic variable and sort incidents from 2009-2019 and 2020-2024. Use a t-test to compare the frequency of each animal instance for each time period.

2.  How is the location of the incident associated with cost?

    May include: `borough`, `hourly_notional_cost`, `incident_notional_cost`

    Tentative plan: facet by borough and find the average incident cost for each. Use Anova

3.  How is the type of incident associated with the time of year?

    May include: `date_time_of_call`, `special_service_type_category` (type of incident)

    Tentative plan: filter date_time_of_call into the four seasons. Then use a test for chi square independence?

## Group Contract

-   How will you communicate? Email? Text? Discord? Meet in person or via Zoom?

    Communicate via text, meet in person, and on Zoom as needed.

-   How often will you be expected to check for updates from your group members?

    Once per week and prior to deadlines.

-   Will there be a group leader, or will this task be rotated in some way? How will you ensure that all project deadlines are met?

    We will share project leadership and keep each other accountable with deadlines.

-   Discuss a timeline for completion. Each of you have busy lives, so discuss schedules in order to try and avoid overwhelming someone with work during a period of time, or to plan ahead if someone is going to be gone at some point.

    We will aim to complete checkpoints two days prior to the deadlines, allowing room for flexibility. We aim to complete the entire project several days before the deadline. There are no scheduled absences within our group.

-   How will all group members work collaboratively on this project through the course of the project? Will you share ideas using Google Docs? Will you create a GitHub repository? Some other way? Please explain.

    We have established a GitHub repository and Quarto files for each checkpoint.

-   Who will be assigned to submit the different components of the group project into Canvas?

    Jett

-   What will be your group's policy, if any, on covering for one another if need be (for example, say someone is sick, or has a family emergency)?

    Upon illness or emergency of a group member, the group has agreed to cover their work if they are unable to complete it asynchronously.

-   What policy will you have in place to resolve any intragroup conflict that may arise (for example, if a group member neglects to carry out their delegated duties to post their results on time, or if a group member is not receiving or responding to group updates as often as expected in item 2 above)? Here are a few options for consideration: warning to the offender, reduction of points, zero credit for the repeat offender, etc. You may use the instructor as a higher court of appeals -- but you will be first expected to document that you implemented your initial conflict resolution plans per your contract and to update the instructor on the outcomes of your own attempts to resolve the conflict.

    -   The first "strike" will be a warning of sorts- someone will reach out to the person and remind them of their delegated duty.

    -   The second "strike" will be a team meeting where the group can discuss assignment delegations and hopefully come to a new/better agreement that suits everyone.

    -   The third "strike" will be approaching Dr. Robinson for assistance.
